### PR TITLE
Add categories to resources

### LINKED ISSUE #46: Categories

### PR DESCRIPTION
**Pull request by Dynnammo**
https://metabase.osp.dev/model/3310-categorisations

Links of modified models:
Proposals : [metabase.osp.dev/model/3160-propositions](https://metabase.osp.dev/model/3160-propositions)
Meetings: [metabase.osp.dev/model/3156-rencontres](https://metabase.osp.dev/model/3156-rencontres)
Debates : [metabase.osp.dev/model/3162-debats](https://metabase.osp.dev/model/3162-debats)
Budgets projects : [metabase.osp.dev/model/3167-projets-des-budgets](https://metabase.osp.dev/model/3167-projets-des-budgets)

closes #46

### CODE REVIEW

**Review by simonaszilinskas — CHANGES_REQUESTED** [review]
check if we can relocate categories on corresponding contributions

**Comment by Dynnammo** [comment]
Added for `proposals` and `budgets_projects`

**Review by Fujistone — COMMENTED** [review]
perfect, good job

**Comment by Dynnammo** [comment]
Links of modified models:
Proposals : https://metabase.osp.dev/model/3160-propositions
Meetings: https://metabase.osp.dev/model/3156-rencontres
Debates : https://metabase.osp.dev/model/3162-debats
Budgets projects : https://metabase.osp.dev/model/3167-projets-des-budgets

**Review by simonaszilinskas — APPROVED** [review]

**Pull request merged**
